### ISSUE TITLE
ArgmentedEvent.prototype.update method a little bit verbose.

### ISSUE THREAD

**Issue by adaniliuk** [yahoo/subscribe-ui-event#21]
Hello,

ArgmentedEvent.prototype.update method is a little bit verbose. It contains console.log call logging scroll.top property into the console. Is it possible to make this logging configurable? Or remove if not necessary?

https://github.com/yahoo/subscribe-ui-event/blob/f2f53863b185132b88aedbbd6476d886e5e259b3/src/AugmentedEvent.js#L54

Thank you in advance,
Andrei

**Comment by roderickhsiao** [comment]
@hankhsiao Can we remove the `console.log` from update?
I remember the `console.log` is added for some purpose (not debugging purpose) but couldn't recall.
We should probably add better comments if it is on purpose or remove it.

**Comment by adaniliuk** [comment]
Thanks a lot for the fix.
