### ISSUE TITLE
Use lodash instead of individual lodash packages

### ISSUE THREAD

**Issue by redonkulus** [yahoo/subscribe-ui-event#25]
@hankhsiao @roderickhsiao 

Its better to just require lodash and then change the require to target the library needed. Right now, with [lodash.clone](https://github.com/yahoo/subscribe-ui-event/blob/master/package.json#L28) pulled in as a separate package, it introduces duplicate clone libraries bundled to the client (assuming another library is pulling in lodash).

**Comment by redonkulus** [comment]
Opened https://github.com/yahoo/subscribe-ui-event/pull/26 to fix it

**Comment by roderickhsiao** [comment]
:+1:
