### ISSUE TITLE
support passive event

### ISSUE THREAD

**Issue by yurited** [yahoo/subscribe-ui-event#42]
a big/computation intensive `touchStart, touchMove` handler could block following scroll event. 

Developers can now annotate touch and wheel listeners with `{passive: true}` to indicate that they will never invoke `preventDefault`. This feature shipped in *Chrome 51, Firefox 49 and landed in WebKit*.

> in Chrome for Android 80% of the touch events that block scrolling never actually prevent it. 10% of these events add more than 100ms of delay to the start of scrolling, and a catastrophic delay of at least 500ms occurs in 1% of scrolls.

spec:
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
https://dom.spec.whatwg.org/#dom-eventlisteneroptions-passive

scroll performance comparison between passive:true and false 
https://www.youtube.com/watch?v=NPM6172J22g

polyfill
```js
// Test via a getter in the options object to see 
// if the passive property is accessed
var supportsPassive = false;
try {
  var opts = Object.defineProperty({}, 'passive', {
    get: function() {
      supportsPassive = true;
    }
  });
  window.addEventListener("test", null, opts);
} catch (e) {}

// Use our detect's results. 
// passive applied if supported, capture will be false either way.
elem.addEventListener(
  'touchstart',
  fn,
  supportsPassive ? { passive: true } : false
); 
```

react is yet to support passive event
https://github.com/facebook/react/issues/6436

**Comment by redonkulus** [comment]
@yurited you want to PR this?

**Comment by yurited** [comment]
yes

**Comment by redonkulus** [comment]
Fixed via https://github.com/yahoo/subscribe-ui-event/pull/44
