### ISSUE TITLE
Change package.json Deprecated licenses tag

### ISSUE THREAD

**Issue by Gravedigger7789** [yahoo/subscribe-ui-event#75]
Would you be able to update your license in [package.json](https://github.com/yahoo/subscribe-ui-event/blob/master/package.json#L79) from
`"licenses": "BSD-3-Clause"`
to
`"license": "BSD-3-Clause"`

I am generating the ThirdParty attributions with https://github.com/microsoft/license-checker-webpack-plugin and it doesn't  support the deprecated licenses field.

**Comment by redonkulus** [comment]
@Gravedigger7789 fixed now, sorry for missing this one.
